services:
  bot:
   build: ./
   volumes:
    - .:/bot
  restart: always
  voice:
    image: voicevox/voicevox_engine:cpu-latest
    platform: linux/amd64
    ports:
      - 50021:50021
    restart: always
